config/routes.rb
Ims::Application.routes.draw do
  
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "welcomes/index"
  root "welcomes#index"

  devise_for :user, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords" }
  
  resources :tickets

  get "createTicketForUser", :to => "tickets#newTicket", as: :tickets_newTicket
  post "createTicketInDirectly", :to => "tickets#createTicketInDirectly"

  devise_scope :user do
    delete 'user/:id', to: 'users/registrations#destroyUser', as: :user_destroy
  end
  

end

app/views/shared/_head.html.haml
%title Ims
= stylesheet_link_tag    "application", media: "all"
= javascript_include_tag "application"
= csrf_meta_tags

app/views/shared/_header.html.haml
%div.header.container
	%ul.nav.nav-pills.navbar-text.pull-left
		%li.active
			=link_to root_path, class: 'dropdown-toggle' do
				Ticket System
		-if user_signed_in?
			%li.dropdown
				=link_to tickets_path, class: 'dropdown-toggle', :data => {:toggle => "dropdown"} do
					Your Generated Tickets
					%span.caret
				%ul.dropdown-menu
					%li
						=link_to 'All Tickets', tickets_path
					%li.divider			
					%li
						=link_to 'Generate Ticket', new_ticket_path
			-if current_user.has_role? :admin and current_user.user_type == "Support"
				%li.dropdown
					=link_to tickets_path, class: 'dropdown-toggle', :data => {:toggle => "dropdown"} do
						Check Tickets Status
						%span.caret
					%ul.dropdown-menu
						%li
							=link_to 'See All Tickets', tickets_allTickets_path
	%div.navbar-text.pull-right
		-if user_signed_in?
			- user = current_user
			%div.btn-group
				%button.btn.btn-success.dropdown-toggle{ :type => "button", :data => {:toggle => "dropdown"}}
					-if ! user.first_name.blank?
						="#{user.first_name}"
					-else
						="#{user.last_name}"
					%span.glyphicon.glyphicon-chevron-down
				%ul.dropdown-menu{role: "menu"}
					%li
						=link_to 'Edit Profile', edit_user_registration_path
					%li.divider
					-if current_user.user_type == "Support" and current_user.has_role? :admin
						%li
							=link_to "Dashboard", rails_admin_path, :class => 'navbar-link'
					%li.divider

					%li
						=link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
					%li.divider
					%li
						=link_to "Delete My Account", user_destroy_path(user.id), :class => "navbar-link text-info", :data => { :confirm => "Are you sure?" }, :method => :delete
		-else
			= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary navbar-link'
			= link_to "Login", new_user_session_path, :class => 'btn btn-primary navbar-link'	

app/views/shared/_notices.html.haml
-if(flash[:notice].blank? == false)
	%div.alert.alert-dismissable.alert-warning.text-center
		%button.close{:href => "#", :data => {:dismiss => "alert"}, :aria=> {:hidden => "true"}}
			&times;
		%span
			=flash[:notice]
-if(flash[:alert].blank? == false)
	%div.alert.alert-dismissable.alert-danger.text-center
		%button.close{:href => "#", :data => {:dismiss => "alert"}, :aria=> {:hidden => "true"}}
			&times;
		%span
			=flash[:alert]
-if(flash[:success].blank? == false)
	%div.alert.alert-dismissable.alert-success.text-center
		%button.close{:href => "#", :data => {:dismiss => "alert"}, :aria=> {:hidden => "true"}}
			&times;
		%span
			=flash[:success]