config/routes.rb
Ims::Application.routes.draw do
  
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "welcomes/index"
  root "welcomes#index"

  devise_for :user, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords" }
  
  resources :tickets

  get "createTicketForUser", :to => "tickets#newTicket", as: :tickets_newTicket
  post "createTicketInDirectly", :to => "tickets#createTicketInDirectly"

  devise_scope :user do
    delete 'user/:id', to: 'users/registrations#destroyUser', as: :user_destroy
  end
  

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

	belongs_to :requester, :class_name => "User"
	belongs_to :creater, :class_name => "User"

	has_many :ticket_assignments, dependent: :destroy

end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base

	validates :name, uniqueness: true,  presence: true, length: {minimum: 2, maximum: 30}

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	before_action :isAdmin, if: :user_signed_in?, only:[:newTicket]

	##  For Support User
	def newTicket
		@ticket = Ticket.new	
	end


	def createTicketInDirectly
		@ticket = Ticket.new(tickets_params)
		@ticket.creater_id = current_user.id
		binding.pry
		user = User.find_by_first_name(@ticket.ticket_user_name)
		binding.pry
		@ticket.requester_id = user.id
		binding.pry
		@ticket.ticket_status = true
		if @ticket.save
			flash[:success] = "Your Ticket is Generated"
			redirect_to root_path
		else
			flash[:alert] = "Error in your Ticket"
			render :new
		end
	end
	## For Support User


	## For Normal User
	def new
		@ticket = Ticket.new
	end

	def create
		@ticket = Ticket.new(tickets_params)
		@ticket.creater_id = current_user.id
		@ticket.requester_id = current_user.id
		binding.pry
		@ticket.ticket_status = true
		if @ticket.save
			flash[:success] = "Your Ticket is Generated"
			redirect_to root_path
		else
			flash[:alert] = "Error in your Ticket"
			render :new
		end
	end

	def index
		# See Ticket for Sngle User
		@allTickets = current_user.requested_tickets
	end

	def show
		@ticket = Ticket.find(params[:id])
	end

	def allTickets
		@allTickets = Ticket.all.order('id DESC')
	end

	
	private

	def tickets_params
		params.require(:ticket).permit(:ticket_user_name, :ticket_user_email, :ticket_user_contact_number, :ticket_title, :ticket_description, :ticket_type, :ticket_sub_type)
	end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_formForIndirectTicket.html.haml
=form_for :ticket, url:{action: "createTicketInDirectly", :method => "post", :controller => "tickets"}, html:{class: "form-horizontal"} do |f|
	%div.form-group
		=f.label 'Select User First Name', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.select(:ticket_user_name , User.all.map {|d| "#{d.first_name}"}, {}, {:class => "form-control"})
	%div.form-group
		=f.label 'Select User Email', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.select(:ticket_user_email , User.all.map {|d| "#{d.email}"}, {}, {:class => "form-control"})
	%div.form-group
		=f.label 'Select User Contact Number', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.select(:ticket_user_contact_number , User.all.map {|d| "#{d.contact_number}"}, {}, {:class => "form-control"})
	%div.form-group
		=f.label :ticket_title, 'Ticket Title', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.text_field :ticket_title , {:class => "form-control", :placeholder => "Issue Title"}
	%div.form-group
		=f.label :ticket_description, 'Ticket Description', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.text_area :ticket_description , {:class => "form-control", :placeholder => "Ticket Description"}
	%div.form-group
		=f.label :ticket_type, 'Ticket Type', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.select(:ticket_type, TicketType.all.map {|d| "#{d.name}"}, {}, {:class => "form-control"})
	%div.form-group
		=f.label :ticket_sub_type, 'Ticket Sub Type', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.select(:ticket_sub_type, TicketSubType.all.map {|d| "#{d.name}"}, {}, {:class => "form-control"})
	%div.form-group
		%div.col-lg-offset-2.col-lg-10
			=f.submit :class => 'btn btn-primary'
			= link_to root_path do
				= content_tag :button, class: "btn btn-danger" do
					="Cancel"

app/views/tickets/_formForTicket.html.haml
=form_for :ticket, url:{action: "create", :controller => "tickets"}, html:{class: "form-horizontal"} do |f|
	%div.form-group
		=f.label :ticket_user_name, 'Ticket User First Name', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.text_field :ticket_user_name , {:class => "form-control", :value => current_user.first_name, readonly: true}
	%div.form-group
		=f.label :ticket_user_email, 'Ticket User Email', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.email_field :ticket_user_email, {:class => "form-control", :value => current_user.email, readonly: true}
	%div.form-group
		=f.label :ticket_user_contact_number, 'Ticket User Contact Number', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.text_field :ticket_user_contact_number, {:class => "form-control", :value => current_user.contact_number, readonly: true}
	%div.form-group
		=f.label :ticket_title, 'Ticket Title', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.text_field :ticket_title , {:class => "form-control", :placeholder => "Issue Title"}
	%div.form-group
		=f.label :ticket_description, 'Ticket Description', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.text_area :ticket_description , {:class => "form-control", :placeholder => "Ticket Description"}
	%div.form-group
		=f.label :ticket_type, 'Ticket Type', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.select(:ticket_type, TicketType.all.map {|d| "#{d.name}"}, {}, {:class => "form-control"})
	%div.form-group
		=f.label :ticket_sub_type, 'Ticket Sub Type', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			=f.select(:ticket_sub_type, TicketSubType.all.map {|d| "#{d.name}"}, {}, {:class => "form-control"})
	%div.form-group
		%div.col-lg-offset-2.col-lg-10
			=f.submit :class => 'btn btn-primary'
			= link_to root_path do
				= content_tag :button, class: "btn btn-danger" do
					="Cancel"

app/views/tickets/allTickets.html.haml
-if current_user.has_role? :admin
	%div.well
		%h1.text-center
			="Status Of All Tickets"
		%br
		-if @allTickets.blank?
			%p.text-center
				No Ticket Generated
		-else
			%div
				%table.table.table-hover.table-condensed.text-center
					%tr
						%th.text-center
							User First Name
						%th.text-center
							User Email
						%th.text-center
							User Contact Number
						%th.text-center
							Ticket Title
						%th.text-center
							Ticket Description
						%th.text-center
							Ticket Start Time
						%th.text-center
							Ticket Status
						%th.text-center
							Ticket Close Time
						%th.text-center
							Options
					-@allTickets.each do |aTicket|
						%tr
							%td= aTicket.ticket_user_name
							%td= aTicket.ticket_user_email
							%td= aTicket.ticket_user_contact_number
							%td= aTicket.ticket_title
							%td= aTicket.ticket_description
							%td= aTicket.created_at.localtime
							-if aTicket.ticket_status == true
								%td= "ON"
								%td= "Ticket is opened"
								%td
							-else
								%td= "Close"
								%td= aTicket.updated_at.localtime
								%td= "Ticket is Closed"

app/views/tickets/index.html.haml
%div.well
	%h1.text-center
		="#{current_user.first_name} Tickets"
	%br
	-if @allTickets.blank?
		%p.text-center
			No Ticket Generated
	-else
		%div
			%table.table.table-hover.table-condensed.text-center
				%tr
					%th.text-center
						User First Name
					%th.text-center
						User Email
					%th.text-center
						User Contact Number
					%th.text-center
						Ticket Title
					%th.text-center
						Ticket Description
					%th.text-center
						Ticket Start Time
					%th.text-center
						Ticket Status
					%th.text-center
						Ticket Close Time
					%th.text-center
						Options
				-@allTickets.each do |aTicket|
					%tr
						%td.info= aTicket.ticket_user_name
						%td.info= aTicket.ticket_user_email
						%td.info= aTicket.ticket_user_contact_number
						%td.info= aTicket.ticket_title
						%td.info= aTicket.ticket_description
						%td.info= aTicket.created_at.localtime
						-if aTicket.ticket_status == true
							%td.info= "ON"
							%td.info
						-else
							%td.info= "Close"
							%td.info= aTicket.updated_at.localtime
						%td.info
							= link_to ticket_path(aTicket.id) do
								= content_tag :button, :class => "btn btn-primary" do
									= content_tag :span, class: "glyphicon glyphicon-list" do
										=""

app/views/tickets/new.html.haml
%br
%h1.text-center
	Generate Ticket
%br
%div.well
	=render "formForTicket"

app/views/tickets/newTicket.html.haml
%br
%h1.text-center
	Generate Ticket
%br
%div.well
	=render "formForIndirectTicket"

app/views/tickets/show.html.haml
%div.well
	%h1.text-center
		="Ticket Title: #{@ticket.ticket_title} Tickets"
	%br
	-if @ticket.blank?
		%p.text-center
			No Ticket Generated
	-else
		%div.container
			%div.list-group.col-lg-10
				%a.list-group-item
					%p.list-group-item-heading.text-center
						Ticket Status
					%h4.list-group-item-text.text-center.text-success
						-if(@ticket.ticket_status == true)
							="ON"
							%br
							="Ticket Start Time: #{@ticket.created_at.localtime}"
						-else
							="Close"
							%br
							="Ticket Start Time: #{@ticket.created_at.localtime}"
							%br
							="Ticket Close Time: #{@ticket.updated_at.localtime}"
			%div.list-group.col-lg-5
				%a.list-group-item
					%p.list-group-item-heading
						First Name
					%h4.list-group-item-text
						-if(@ticket.ticket_user_name.blank?)
							="--"
						-else
							=@ticket.ticket_user_name.capitalize
			%div.list-group.col-lg-5
				%a.list-group-item
					%p.list-group-item-heading
						Email
					%h4.list-group-item-text
						-if(@ticket.ticket_user_email.blank?)
							="--"
						-else
							=@ticket.ticket_user_email
			%div.list-group.col-lg-5
				%a.list-group-item
					%p.list-group-item-heading
						Contact Number
					%h4.list-group-item-text
						-if(@ticket.ticket_user_contact_number.blank?)
							="--"
						-else
							=@ticket.ticket_user_contact_number.capitalize
			%div.list-group.col-lg-5
				%a.list-group-item
					%p.list-group-item-heading
						Ticket Description
					%h4.list-group-item-text
						-if(@ticket.ticket_description.blank?)
							="--"
						-else
							=@ticket.ticket_description.capitalize